openapi: 3.0.0
info:
  title: Interoperability components Italy
  description: |
    OpenAPI 3 templates and definitions for implementing
    interoperable APIs.

    The work is ongoing, your feedback is greatly appreciated!
