#
# CircleCI buildfile. Run locally with
#
#   circleci-local build
#
version: 2
jobs:
  build:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Build definitions.yaml
          command: |
            pip install tox
            tox

      # Update gh-pages
      - run:
          name: "Update GitHub Pages"
          command: |
            if [ "${CIRCLE_BRANCH#test-}" != "${CIRCLE_BRANCH}" ]; then
              make ghpages
            fi


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*?/

